//video
const SET_TEXT_SEARCH = 'SET_TEXT_SEARCH';

//search
const GET_FIRST_VIDEO = 'GET_FIRST_VIDEO'; 

//TO_DO_LIST

const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
const ADD_TODO_STARTED = 'ADD_TODO_STARTED';
const DELETE_TODO = 'DELETE_TODO';


export {
    SET_TEXT_SEARCH,
    GET_FIRST_VIDEO,
    ADD_TODO_SUCCESS,
    ADD_TODO_FAILURE,
    ADD_TODO_STARTED,
    DELETE_TODO
}